age = input("What is your age? ")
print("Thank you.")
print(age)
print(type(age))
print("This number has " + str(len(age)) + " characters.")
age = int(age)
print(age)
age = float(age)
print(age)
age = str(age)